### PR TITLE
Portfolio: Application Deploy

### PR DESCRIPTION
**Pull request by Kambuchi**
## **Update Readme & Screenshot**

- Add link to live demo.
- Update screenshot.

### CODE REVIEW

**Review by vichuge — CHANGES_REQUESTED** [review]
# Required Changes ♻️ ⚠️ 🚦 

Hi @Kambuchi, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

mario_ladders

## Good points 👍 
- No Linters error ✔️ 

## Aspects to improve ♻️

- [ ] It looks like the mobile size on deployment needs to improve, if you observe the image, you could note that the mobile size is right-oriented, making it impossible to observe as is required. I kindly invite you to work on this 😄 
image

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
Hi @Kambuchi 😃,  

## Required Changes

The live demo link is working fine but there's still space for improvement on your page on the mobile version as suggested by the previous reviewer. I highly suggest that you work on that!

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Kambuchi** [comment]
> Hi @Kambuchi 😃,
> 
> ## Required Changes
> The live demo link is working fine but there's still space for improvement on your page on the mobile version as suggested by the previous reviewer. I highly suggest that you work on that!
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Can you show me what is not working? I already checked and on my computer seems correct 

127 0 0 1_5500_index html(Galaxy S5)

 And thanks.

**Review by Shaher-11 — CHANGES_REQUESTED** [review]
#### Hello @Kambuchi,

### Great work on making the changes requested by the previous reviewer:clap::clap::clap:
You've done a good job implementing some of the requested changes but there are still some which aren't done yet,  so we need to implement those changes to get the project approved:muscle::muscle::muscle:

 ## Required Changes ♻️

- [ ] The mobile version of the website does not look like the original design at all
- [ ] Check the screenshots below  below:point_down:

wrong1


wrong2

wrong4

wrong5



Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Happy Coding!👏👏👏

**Review by Temmarie — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUIRED! :recycle:

### Hi @Kambuchi     ! :wave: :wave:

#### You have done really well in implementing these requirements.
- You used proper GitHub Flow ✔️ 
- Your linter checks are all passing ✔️ 
- Your README and PR message are descriptive ✔️ 

 However, you have not implemented the previously requested changes. Kindly make those changes and submit for review. 
- - -

### **Required Changes** ♻️
- [ ] You have a horizontal overflow that is messing with the project's orientation on desktop and mobile screens but mostly on the mobile screens. Kindly make this change. As this is the fourth review, you will have to repeat the week as mentioned in the code review policy. 


### Optional Changes 👌
Every comment with the OPTIONAL prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend that you take them into account as they can make your code better.
- N/A

_If anything doesn't seem clear to you, feel free to leave your question or comment in the PR thread below_

**_"Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise."_**
- - - 
**Note that you still have exceeded the number of reviews as written in the [Code Reviews Limit Policy](https://microverse.zendesk.com/hc/en-us/restricted?return_to=https%3A%2F%2Fmicroverse.zendesk.com%2Fhc%2Fen-us%2Farticles%2F1500004088561), however, if you feel this review is unfair, you can request a second opinion using [this](https://airtable.com/shrQAqnBwek5a0O0s) form.**

__Kindly make the necessary changes and submit another code review request.__

**Comment by Davidosky007** [comment]
Hi @Kambuchi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏
[OPTIONAL]
* Although this is an optional suggestion i would strongly advise you to fix these differences in your design, you should stick to the original design as much as possible 👍 
* the text area and the horizontal overflow on the desktop view
Screenshot (93)
Screenshot (94)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
